### ISSUE TITLE
add:  Real Code Camp  - is a Online Opensource Bootcamp

### ISSUE THREAD

**Issue by developerfred** [CollabCodeTech/quarentena-tech#2]
## The problem 

There are currently thousands of developers starting their careers, not knowing where to start and to start this developer needs a large amount of available time and money to pay for courses that cost up to $ 11,000 a year. This is very expensive for a young person who is starting a career or for someone who is changing areas and migrating to a career in technology. The market is very heated and this gives rise to N platforms, frameworks, companies etc. But with all this information, the young man asks himself, "Where can I start? Do I need to study python? Do I need to study algorithms?"

### We can focus on some important issues:

- price
- Idiom
- learning curve 
- new languages. 

### The solution 

Real Code Camp is a mentoring platform "on the road" which means "on the move". We are attentive to the market and the changes that occur on a daily basis and our main focus is to encourage developers to develop technology for web 3.0 and web 4.0, so we will go through all branches of technology working with real projects. Today there are thousands of issues open on github. Among these issues there are problems that pay for each solution. We at Real Code Camp help developers to contribute to the open source world and get paid for it. We believe that a more inclusive and participatory movement begins to transform the technology of the future once and for all.

Read in[ portuguese](http://bit.ly/RealCodeCampVersion-01)
---
https://realcodecamp.xyz
http://bit.ly/gitcoinRealCodeCamp
http://bit.ly/RealCodeCampGroup

**Comment by MarcoBrunoBR** [comment]
I'm sorry. This site is to content portuguese
